name: online_benchmark
type: online  # Test type: offline, online, eval, submission | options: offline, online, eval, submission
model_params:
  name: '<MODEL_NAME eg: meta-llama/Llama-3.1-8B-Instruct>'
datasets:  # Dataset configs
- name: perf
  type: performance  # Dataset purpose: performance or accuracy | options: performance, accuracy
  path: '<DATASET_PATH eg: tests/assets/datasets/dummy_1k.jsonl>'  # Dataset file path
  parser:  # Column remapping: {prompt: <col>, system: <col>}
    prompt: text_input
settings:
  runtime:
    min_duration_ms: 600000  # Min duration (ms, or with suffix: 600s, 10m)
    max_duration_ms: 0  # Maximum test duration in ms (0 for no limit)
    n_samples_to_issue: null  # Sample count override
  load_pattern:
    type: poisson  # Load pattern type | options: max_throughput, poisson, concurrency, multi_turn, burst, step
    target_qps: 10.0  # Target QPS
endpoint_config:
  endpoints:  # Endpoint URL(s). Must include scheme, e.g. 'http://host:port'.
  - http://localhost:8000
